import { FormEvent, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
type Item = { id: string; kind: string; group: string; title: string; description: string; metadata: Record<string, unknown> };
type Content = { items: Item[]; documents: Record<string, any> };
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(path, { ...init, headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || '请求失败'); return body.data; }
export function ContentPage() {
  const client = useQueryClient(); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [group, setGroup] = useState('ideas');
  const content = useQuery({ queryKey: ['content'], queryFn: () => request<Content>('/api/v1/workspaces/default/content') });
  const add = useMutation({ mutationFn: () => request('/api/v1/workspaces/default/content/ideas', { method: 'POST', body: JSON.stringify({ group, title, description }) }), onSuccess: () => { setTitle(''); setDescription(''); client.invalidateQueries({ queryKey: ['content'] }); } });
  const inspirations = useMemo(() => (content.data?.items || []).filter(item => item.kind === 'inspiration'), [content.data]); const comics = useMemo(() => (content.data?.items || []).filter(item => item.kind === 'comic_published'), [content.data]); const top = useMemo(() => (content.data?.items || []).filter(item => item.kind === 'review_top'), [content.data]);
  const submit = (event: FormEvent) => { event.preventDefault(); if (title.trim()) add.mutate(); };
  return <main className="shell task-shell"><div className="eyebrow">CONTENT · SQLITE API</div><h1>内容创作中心</h1><p>选题、复盘和 AI 漫剧数据已经由 API 统一管理。</p><form className="content-form" onSubmit={submit}><select value={group} onChange={e => setGroup(e.target.value)} aria-label="灵感分组"><option value="ideas">选题灵感</option><option value="trends">热点趋势</option><option value="sources">创作来源</option></select><input value={title} onChange={e => setTitle(e.target.value)} placeholder="记录一个内容灵感" aria-label="内容灵感" /><input value={description} onChange={e => setDescription(e.target.value)} placeholder="补充说明（可选）" aria-label="灵感说明" /><button type="submit" disabled={add.isPending}>{add.isPending ? '保存中…' : '添加'}</button></form>{(content.error || add.error) && <div className="error-card" role="alert">{(content.error || add.error)?.message}</div>}{content.data && <><section className="idea-grid"><h2>灵感库 <small>{inspirations.length}</small></h2>{inspirations.map(item => <article key={item.id}><h3>{item.title}</h3><p>{item.description || '尚未补充说明'}</p><small>{item.group}</small></article>)}</section><section className="idea-grid"><h2>内容复盘</h2>{top.map(item => <article key={item.id}><h3>{String(item.metadata.rank || '')} {item.title}</h3><p>{item.description}</p></article>)}</section><section className="idea-grid"><h2>AI 漫剧</h2>{content.data.documents.comic_current && <article><h3>{content.data.documents.comic_current.title || '当前项目'}</h3><p>分镜进度：{content.data.documents.comic_current.storyboards || '未设置'}</p></article>}{comics.map(item => <article key={item.id}><h3>{item.title}</h3><p>{item.description}</p></article>)}</section></>}</main>;
}
